### PR TITLE
Fix invalid RepairSegment states stored in Cassandra / Postgres / H2

### PR DESCRIPTION
**Pull request by michaelsembwever**
This ensures segments read from Cassandra satisfy the preconditions in `RepairSegment.Builder.build()`

The Migration009 process could take some time on large clusters.

### CODE REVIEW

**Review by adejanovski — CHANGES_REQUESTED** [review]
Fixing the Cassandra DB won't be enough as the problem also arises when upgrading with the Postgres backend (and most probably H2), as shown in PR #260

**Comment by michaelsembwever** [comment]
> Fixing the Cassandra DB won't be enough as the problem also arises when upgrading with the Postgres backend (and most probably H2), as shown in PR #260

Doesn't #260 fix it for postgres and H2? While this PR fixes it just for Cassandra.

EDIT: it doesn't. #260 contains an additional comment describing a new fault.

**Comment by adejanovski** [comment]
@anguenot : the PR is ready to be tested when you have time.

Thanks !

**Comment by anguenot** [comment]
@adejanovski this PR definitely addresses the issue and the upgrade went through this time. Thanks!

**Review by adejanovski — APPROVED** [review]

**Pull request merged**
