### PR TITLE
Fix the redirect for the custom ingress path, post Reaper UI login

### PR DESCRIPTION
**Pull request by Jenishk56**

### CODE REVIEW

**Comment by Jenishk56** [comment]
@terrcin  Can you please review this and help me merge if possible ?

**Comment by Jenishk56** [comment]
@nsteinmetz @elsmorian @mattnworb @terrcin 
Hey guys, This is something I would like to fix as being an individual contributor. Please have a look and let me know if you have any concerns or queries.

**Comment by nsteinmetz** [comment]
I no longer work on Reaper (last customers don't use Cassandra nor Reaper as a consequence)  - maybe @adejanovski can help on this?

**Comment by adejanovski** [comment]
Hi @Jenishk56,

thanks for sending this PR!
Is there a related issue that would give some background info on what specific case we're trying to fix here?
If not, would you mind creating one that we'll attach this PR to?

Thanks again

**Comment by Jenishk56** [comment]
@adejanovski 
Thanks for getting back.

Issue details:=

If I use the custom path e.g. /XYZ/reaper instead of the default (/) on my ingress, I can see the login page fine on `<BASE_URL>/XYZ/reaper/webui/login.html` but after login, it automatically redirects to `<BASE_URL>/webui/index.html`

I believe that is because it doesn't have the contextPath post login. If you can see my changes on `src/ui/app/jsx/login-form.jsx`, I tried to add the context path post login which should help me redirecting to proper path - `<BASE_URL>/XYZ/reaper/webui/index.html`

Hope this helps. Please do let me know if you need more details.

**Comment by Jenishk56** [comment]
@nsteinmetz @elsmorian @mattnworb @terrcin

**Review by adejanovski — APPROVED** [review]
LGTM.

Could you please squash your commits into a single one before I merge the PR?

Thanks!

**Comment by Jenishk56** [comment]
@adejanovski

I think, I made it difficult due to merge commit and squash. Can i please create another PR ?

**Comment by adejanovski** [comment]
Of course @Jenishk56, close this PR and make a new one if that's easier for you 👍

**Comment by Jenishk56** [comment]
Creating new PR

**Pull request closed without merging**
