### PR TITLE
Fix navBar

### LINKED ISSUE #468: [1.2.0] Cannot resolve module 'jsx/navbar'
To debug #467, I set up a local envt for the app - When trying to run the server, I have 

```
ERROR in ./app/jsx/schedule-screen.jsx
Module not found: Error: Cannot resolve module 'jsx/navbar' in /Users/nsteinmetz/Documents/Projets/cassandra/cassandra-reaper/src/ui/app/jsx
 @ ./app/jsx/schedule-screen.jsx 3:0-133:2

ERROR in ./app/jsx/snapshot-screen.jsx
Module not found: Error: Cannot resolve module 'jsx/navbar' in /Users/nsteinmetz/Documents/Projets/cassandra/cassandra-reaper/src/ui/app/jsx
 @ ./app/jsx/snapshot-screen.jsx 3:0-273:2

ERROR in ./app/jsx/repair-screen.jsx
Module not found: Error: Cannot resolve module 'jsx/navbar' in /Users/nsteinmetz/Documents/Projets/cassandra/cassandra-reaper/src/ui/app/jsx
 @ ./app/jsx/repair-screen.jsx 3:0-135:2

ERROR in ./app/jsx/cluster-screen.jsx
Module not found: Error: Cannot resolve module 'jsx/navbar' in /Users/nsteinmetz/Documents/Projets/cassandra/cassandra-reaper/src/ui/app/jsx
 @ ./app/jsx/cluster-screen.jsx 3:0-135:2
```

Indeed, `jsx/navbar.jsx` the file existed til 1.1 but was removed with 1.2

### PR DESCRIPTION
**Pull request by nsteinmetz**
Fix #468 and rebase of #469

### CODE REVIEW

**Review by michaelsembwever — APPROVED** [review]
LGTM

**Comment by nsteinmetz** [comment]
So we all agree that UI is now as below ?

capture d ecran 2018-07-11 a 12 36 27

**Comment by nsteinmetz** [comment]
Also updating the .gitignore so that jsx/navbar.jsx is no longer present - it also explains, why 1.2 did not have the issue when released as file was still present.

**Comment by adejanovski** [comment]
@nsteinmetz : 

> So we all agree that UI is now as below ?

I don't :)
The `navbar.jsx` file is generated by Maven in the `generate-sources` phase  : https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/pom.xml#L461-L478

We do this so we can have the version information there and a "Report a bug" button that issues the commit sha in the description (or title).

If you run a `mvn clean package` you should have everything built as needed.
I was able to build the latest master and not didn't run into #468, with both the server and the webpack-dev-server.
My `navbar.jsx` file got successfully regenerated : 

```
-rw-r--r--  1 adejanovski  staff  24625  4 jul 16:39 schedule-form.jsx
-rw-r--r--  1 adejanovski  staff   9587  4 jul 16:39 schedule-list.jsx
-rw-r--r--  1 adejanovski  staff  14950  4 jul 16:39 segment-list.jsx
-rw-r--r--  1 adejanovski  staff   2438  4 jul 16:39 sidebar.jsx
-rw-r--r--  1 adejanovski  staff  10949  4 jul 16:39 snapshot-form.jsx
-rw-r--r--  1 adejanovski  staff   9639  4 jul 16:39 snapshot-list.jsx
-rw-r--r--  1 adejanovski  staff   7457  4 jul 16:39 snapshot-screen.jsx
-rw-r--r--  1 adejanovski  staff   2351 11 jul 16:31 navbar.jsx
```
We removed it from git because it's a file that shouldn't be tracked as it's generated during build.
I'll close this PR as I think the problem lies somewhere else, so let's track progress on #468.

**Pull request closed without merging**
