### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by pndewit**
- Fixes many toggle menu arrow buttons not clickable (only the link next to it).
- Improves sidebar button labels (plural)
- Changes confusing "Delete cluster" button label to "Forget cluster" as it is not deleting the cluster, just the Cassandra-reaper reference to that cluster.
- Fixed typo in README
- Fixed some labels breaking to a next line for a colon because of screen width
- Fixed initial loading spinner not showing up for repair-list
- Added initial loading spinner for segment-list
- Fixed cluster list state not showing anything when it's empty

### CODE REVIEW

**Comment by pndewit** [comment]
Let me know if you find anything. :)

**Comment by adejanovski** [comment]
LGTM @pndewit 

I guess the use of plurals vs singulars in the sidebar is a matter of taste, but I have no real preference, I'm fine with plurals.

Could you rebase your branch on master ? I've merged in a new datetime picker the other day which must conflict with your changes.

Thanks !

**Comment by pndewit** [comment]
@adejanovski Great, I'll do a rebase right away.
I hear ya, but schedules was plural and the rest singular. Decided to go for plurals as it made more sense to me 😄

**Comment by pndewit** [comment]
@adejanovski Done 👍 
No conflicts.

**Review by adejanovski — APPROVED** [review]

**Comment by adejanovski** [comment]
Merged, thanks @pndewit !

**Pull request merged**
