### PR TITLE
Issue #809 : Allow for JMX Credentials to be strored alongside JMX Po…

### PR DESCRIPTION
**Pull request by denniskline**
…rt in the backend storage system.

This is a fresh PR spun off of:
https://github.com/thelastpickle/cassandra-reaper/pull/817
I had some issues squashing that PR so I cherry-picked into this PR and squashed.

Thank you

### CODE REVIEW

**Comment by adejanovski** [comment]
Hi @denniskline,

I'll shortly run some tests on this PR and merge it if it's all good.

**Review by adejanovski — CHANGES_REQUESTED** [review]
Hi @denniskline,

this is an awesome addition, thanks a lot!
I have 3 small pain points that I think we should address to enforce security:

- By default, encryption is disabled. I think we should never store passwords in plain text in the database, and should fail with an appropriate message if ever someone tried to add a cluster with JMX authentication with encryption off. 
- the sample config files do not include any sample of how to enable encryption (under `src/packaging/resources`)
- Reaper logs all requests and shows the password in plain text : 
`INFO   [2020-01-24 11:18:01,729] [dw-54 - POST /cluster?seedHost=127.0.0.1&jmxPort=7100&jmxUsername=cassandra&jmxPassword=cassandrapassword] i.c.r.ClusterResource - creating new cluster based on given seed host: c3.0.15 `. 
I think we would be fine if the password was sent as post body instead of a query param. It would then not show up in the logs.

Other from these small changes, the PR looks fantastic to me!

**Comment by denniskline** [comment]
@adejanovski great feedback.  I really appreciate you and @michaelsembwever dedicating the time to help hash out this feature.  

New commit has been squashed.  Please let me know if there are any additional changes you would like to see.

Thank you very much

**Comment by adejanovski** [comment]
Hi @denniskline, 

Thanks for making those changes, it's all safe now 👍 
A few more issues:
- Changing the cluster resource as we did there (using form data with the post/put operations) will break backwards compatibility
- spreaper wasn't updated to register clusters the "new" way
- Integration tests are broken because they try to use the old POST operation with query params
- We had no integration tests for various setups arounds jmx credentials (I tested registering with credentials, without credentials, and with credentials but no encryption system env variable)

Here's a commit that fixes all these issues which you can cherry pick : https://github.com/thelastpickle/cassandra-reaper/commit/9d344409243c014dd2000fa14895322cc13e050e

I've updated the API docs to show both operations for PUT/POST in the cluster resource. The version that has JMX credentials was pushed under `/cluster/auth` to distinguish both endpoints.

I tried to push it to your branch directly but you didn't allow committers to push there :) 
Let me know if that works for you.

**Comment by denniskline** [comment]
@adejanovski cherry-pick'd and squashed.  very sorry for breaking backwards compatibility.  thank you again for fixing!!

**Pull request merged**
