### PR TITLE
Upgrade dependencies (Upgrade to DropWizard 1.1.x)

### PR DESCRIPTION
**Pull request by michaelsembwever**
Reason for this PR
 - https://github.com/thelastpickle/cassandra-reaper/issues/224
 - security and bugfixes.

Upgrade dependencies.
 - dropwizard 1.0.8 -> 1.1.7
 - guava 19 -> 20
 - logback 1.2.2 -> 1.2.3
 - javax.mail-api 1.5.6 -> 1.6.6
 - dropwizard-metrics-datadog 1.0.6 -> 1.1.13
 - postgresql 9.3-1104-jdbc41 -> 9.4.1212.jre7
 - cassandra-driver-core 3.1.4 -> 3.5.0
 - cassandra 2.2.7 -> 2.2.12
 - postgresql 9.3-1100-jdbc41 -> 42.2.2.jre7
 - h2 1.4.186 -> 1.4.197
 - cassandra-migration 2.0.0 -> 2.1.2
 - flyway-core 4.0.3 -> 5.1.0
 - prometheus 0.0.25 -> 0.4.0
 - junit 4.11 -> 4.12
 - mockito-core 2.10.0 -> 2.18.3
 - awaitility 2.0.0 -> 3.1.0

Upgrade plugins.
 - maven-surefire-plugin 2.19 -> 2.21.0
 - maven-failsafe-plugin 2.20 -> 2.21.0
 - maven-resources-plugin 3.0.2 -> 3.1.0
 - maven-checkstyle-plugin 2.17 -> 3.0.0
 - docker-maven-plugin 1.0.0 -> 1.1.0
 - maven-shade-plugin 3.0.0 -> 3.1.1
 - maven-jar-plugin 3.0.2 -> 3.1.0
 - error_prone_core 2.1.1 -> 2.3.1
 - plexus-compiler-javac-errorprone 2.8.2 -> 2.8.4

Updated integration tests:
 - tests against postgresql 9.2 -> 9.4

### CODE REVIEW

**Comment by michaelsembwever** [comment]
Good for review, @adejanovski 


Although the dependency tangle in this project is pretty horrific. Typical culprits of Guava, jersey, and dropwizard metrics.
In the future we should look at separate classloaders for the jmx to Cassandra interfaces, so that jmx uses the correct C* dependencies against each version to the cluster in question, isolating a large part of the pain in the dependency tangle.

**Review by adejanovski — DISMISSED** [review]
The server won't start on my laptop : 

```
$ java -jar src/server/target/cassandra-reaper-1.2.0-SNAPSHOT.jar server ~/cassandra-reaper-cassandra.yaml 
Exception in thread "main" java.lang.NoClassDefFoundError: org/glassfish/jersey/server/ResourceConfig
	at io.cassandrareaper.ReaperApplication.initialize(ReaperApplication.java:118)
	at io.dropwizard.Application.run(Application.java:84)
	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:95)
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.server.ResourceConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

**Review by adejanovski — APPROVED** [review]
LGTM, the server runs fine now 👍

**Comment by michaelsembwever** [comment]
@adejanovski shall this be merged now and included in 1.2.0?

**Comment by adejanovski** [comment]
I'm +1 on merging now and release this in 1.2.0.
No need to wait, everything works just fine.

**Pull request merged**
