### PR TITLE
Cassandra performance: Add LCS and row cache

### PR DESCRIPTION
**Pull request by michaelsembwever**
ref:
 - https://github.com/thelastpickle/cassandra-reaper/pull/96
 - https://github.com/thelastpickle/cassandra-reaper/issues/94

### CODE REVIEW

**Comment by adejanovski** [comment]
LCS makes sense since we're mostly reading. 
The way Reaper is implemented we would still have a lot of queries sent when retrieving all segments to get generate new tasks but we could be reading faster overall.
I thought TWCS would be a good fit here but since it's not available by default, it's not possible to add it straight away.

Cache is a smart idea too but unless activated in the cluster's config, we won't benefit from it (and it's turned off by default). 
OK with keeping it since it will do nothing in the worst case, and bring improvements in the best one.

**Comment by adejanovski** [comment]
I have some concerns about the recompactions involved in altering the schema on existing clusters. Not that the reaper db should be very big anyway, but we could trigger a lot of compactions all at once in the worst case.

We could instead modify the existing CQL file and affect only new installs this way. Then users could do the change themselves if required.

What do you think ?

**Comment by rustyrazorblade** [comment]
> I have some concerns about the recompactions involved in altering the schema on existing clusters. Not that the reaper db should be very big anyway, but we could trigger a lot of compactions all at once in the worst case.

I'm not concerned about this.  I feel like it's a premature optimization to try to avoid it.  We should have release notes that warn users about changes like this though.

**Comment by michaelsembwever** [comment]
> I thought TWCS would be a good fit here but since it's not available by default, it's not possible to add it straight away.

But none of the tables are time-series? (not obviously so anyway. i'd be reluctant to introduce that constraint upon the datamodel when it's not obvious to begin with)

**Comment by michaelsembwever** [comment]
> I have some concerns about the recompactions involved in altering the schema on existing clusters. Not that the reaper db should be very big anyway, but we could trigger a lot of compactions all at once in the worst case.

No concerns. The size of the data involved will be small.

**Comment by adejanovski** [comment]
> But none of the tables are time-series? (not obviously so anyway. i'd be reluctant to introduce that constraint upon the datamodel when it's not obvious to begin with)

Right, actually it was on the tables I've added in the ft-reaper branch. Nothing is TTLed here so nevermind :)

**Pull request merged**
