### PR TITLE
Expose Cassandra Node Streams via Reaper

### PR DESCRIPTION
**Pull request by rzvoncek**
This PR gives Reaper the ability to pull information about Cassandra node's ongoing streams. This is done in a fashion similar to @adejanovski's pulling of thread pool stats and dropped messages in #446 (for merging of which this PR needs to wait). A Cassandra node is contacted only after requesting the corresponding stream HTTP endpoint. Reaper won't subscribe to stream notifications as making that work correctly is a much bigger task.

The second commit in this PR adds visualisation of the pulled information in node detail page.

There is now a new URL available for GET requests with format:

    localhost:8080/node/streams/{cluster}/{node}

An example response payload:
```
[
  {
    "planId": "7805a580-8038-11e8-adb7-4751e6155332",
    "streams": {
      "127.0.0.1-OUT-127.0.0.1": {
        "id": "127.0.0.1-OUT-127.0.0.1",
        "host": "127.0.0.1",
        "peer": "127.0.0.2",
        "direction": "OUT",
        "sizeToSend": 130972860,
        "sizeToReceive": 0,
        "sizeSent": 10996145,
        "sizeReceived": 0,
        "progressSent": [
          {
            "table": "keyspace1.standard1",
            "current": 10996145,
            "total": 72803010
          }
        ],
        "progressReceived": [],
        "lastUpdated": 1530784137584,
        "completed": false,
        "success": true
      }
    }
  }
]
```

An example output in the UI:
screen shot 2018-07-05 at 15 33 37

### CODE REVIEW

**Comment by michaelsembwever** [comment]
@rzvoncek this is a solid piece of work! can you look at why all the CI builds are failing?

(it also needs a rebase, after @adejanovski has rebased the #446, and then the base changed to be off #446 . ie this PR as i've understood it should only be 2 commits.)

**Comment by rzvoncek** [comment]
@michaelsembwever, doing a rebase on top of master currently doesn't make sense because this PR just adds a feature to @adejanovski's #446.

**Comment by michaelsembwever** [comment]
>> it also needs a rebase, after @adejanovski has rebased the #446, and then the base changed to be off #446 . ie this PR as i've understood it should only be 2 commits.

> @michaelsembwever, doing a rebase on top of master currently doesn't make sense because this PR just adds a feature to @adejanovski's #446.

Yeah, but that's not what I said :-)
(Rebase against #446, since it had changed underneath you, *and* change the PR's base to `alex/display-node-metrics`.)

Things are different now that #446 has been merged. Can you now rebase against master, please.

**Review by adejanovski — APPROVED** [review]
Tested and approved. Awesome to have this in :)

**Pull request merged**
