### PR TITLE
Support IPv6 Cassandra nodes

### LINKED ISSUE #361: ipv6 support
Please add ipv6 support
`INFO   [2018-03-07 00:52:01,000] [pool-4-thread-4] i.c.j.JmxConnectionFactory - Unreachable host: Failure when establishing JMX connection to 2a02:6b8:b010:61:6807:zzzz:yyyy:xxxx:7199: java.lang.NumberFormatException: For input string: "6b8:b010:61:6807:zzzz:yyyy:xxxx:7199"`

### PR DESCRIPTION
**Pull request by dormidon**
Try to fix #361.

### CODE REVIEW

**Comment by michaelsembwever** [comment]
Looks good! Could we get some unit tests for it too?

**Comment by dormidon** [comment]
Thanks!
Ok, I will try to add tests.

**Comment by adejanovski** [comment]
Hi @dormidon,

thanks a lot for this contribution.
Any chance you could add some tests so we can merge this PR ?

Thanks again !

**Comment by dormidon** [comment]
Hi @adejanovski,
I've tried to add some tests but it was more difficult than it seemed :(
Unfortunately `JmxProxyImpl` class is poorly designed for testing.
I've try several attempts to do it. 
The first attempt was to "expose" `connectWithTimeout(...)` method (mark it `protected`) and mock it. But this requires to make the entire class non-final, or some other refactoring loosely associated with the task.
The second one was test only `getJmxServiceUrl()` method, more precisely 
```
isNumericIPv6Address(host) ? "[" + host + "]" : host
```
expression.
But it looks to be too poor test.

I would be grateful if you prompt me a way to test it properly.

**Comment by adejanovski** [comment]
I agree it can be challenging. 
I think making both `isNumericIPv6Address()` and `getJmxServiceUrl()` protected along with the `@VisibleForTesting` annotation, and writing some unit tests for both IPv6 and IPv4 addresses would already be great. 
We have integration tests that will cover the usage of `connect()` IPv4 connection phases so we'll be protected from potential regressions (they already passed on your PR).

**Comment by dormidon** [comment]
I've extracted `JmxAddresses` class with utility methods `isNumericIPv6Address()` and `getJmxServiceUrl()` and added tests on them.

**Comment by dormidon** [comment]
Thank you for your recommendation and merge!

**Pull request merged**
