### PR TITLE
Topology change resilience for incremental repair

### LINKED ISSUE #1213: Incremental Repair Stalls on Cassandra 4
We recently upgraded our Cassandra clusters to 4.0.4 (from 3.11). We attempted to switch our repair schedules over to incremental given it's now the recommended repair method in 4.0 however we are seeing that incremental repairs appear to stall in Cassandra 4.0 in our environment.

The main symptom of this is that repairs seem to go on as normal until they just "stop" with no apparent error message in Cassandra or Reaper. These repairs persist indefinitely until they are manually aborted in Reaper.

Our environment:
Cassandra 4.0.4 running under the eclipse-temurin 11.0.15_10-jre JVM (Ubuntu Jammy container)
Reaper 3.1.1 running as a sidecard (also tested with container built from git master)
Three nodes spread across different AWS AZs (but configured to be part of the same Cassandra datacenter)

Repairs were created with the following settings:

* Targeting a single keyspace (glowroot for our example)
* Incremental TRUE
* Adaptive TRUE (not sure if this does anything with incremental repairs)
* Concurrency Parallel
* Thread count 4

Cassandra system logs (these started recording just before the repair was started, and go until about thirty minutes after the last entry about repair is mentioned, at which point the repair was assumed to be stalled as we've never seen a repair recover after that point):
[cassandra-0.log](https://github.com/thelastpickle/cassandra-reaper/files/9075217/cassandra-0.log)
[cassandra-1.log](https://github.com/thelastpickle/cassandra-reaper/files/9075216/cassandra-1.log)
[cassandra-2.log](https://github.com/thelastpickle/cassandra-reaper/files/9075215/cassandra-2.log)

Reaper logs are essentially just this on every reaper container (repeated until the repair is canceled) with no actual errors:

```
INFO   [2022-07-08 20:55:33,093] [cassandra:4ecfb200-ff00-11ec-a134-1b2df3c07864] i.c.s.RepairRunner - Attempting to run new segment... 
INFO   [2022-07-08 20:55:33,252] [cassandra:4ecfb200-ff00-11ec-a134-1b2df3c07864] i.c.s.RepairRunner - Next segment to run : 4ed04e40-ff00-11ec-a134-1b2df3c07864 
INFO   [2022-07-08 20:56:12,181] [cassandra:4ecfb200-ff00-11ec-a134-1b2df3c07864] i.c.s.RepairRunner - Attempting to run new segment... 
INFO   [2022-07-08 20:56:12,341] [cassandra:4ecfb200-ff00-11ec-a134-1b2df3c07864] i.c.s.RepairRunner - Next segment to run : 4ed07550-ff00-11ec-a134-1b2df3c07864 
INFO   [2022-07-08 20:56:32,667] [SchedulingManagerTimer] i.c.s.SchedulingManager - Repair schedule '5147f450-fe58-11ec-97bf-51955d7aec44' is paused 
INFO   [2022-07-08 20:56:47,678] [cassandra:4ecfb200-ff00-11ec-a134-1b2df3c07864] i.c.s.RepairRunner - Attempting to run new segment... 
INFO   [2022-07-08 20:56:47,775] [cassandra:4ecfb200-ff00-11ec-a134-1b2df3c07864] i.c.s.RepairRunner - Next segment to run : 4ed07550-ff00-11ec-a134-1b2df3c07864 
INFO   [2022-07-08 20:57:26,639] [cassandra:4ecfb200-ff00-11ec-a134-1b2df3c07864] i.c.s.RepairRunner - Attempting to run new segment... 
INFO   [2022-07-08 20:57:26,764] [cassandra:4ecfb200-ff00-11ec-a134-1b2df3c07864] i.c.s.RepairRunner - Next segment to run : 4ed04e40-ff00-11ec-a134-1b2df3c07864 
INFO   [2022-07-08 20:57:32,741] [SchedulingManagerTimer] i.c.s.SchedulingManager - Repair schedule '5147f450-fe58-11ec-97bf-51955d7aec44' is paused 
INFO   [2022-07-08 20:58:06,369] [cassandra:4ecfb200-ff00-11ec-a134-1b2df3c07864] i.c.s.RepairRunner - Attempting to run new segment... 
INFO   [2022-07-08 20:58:06,439] [cassandra:4ecfb200-ff00-11ec-a134-1b2df3c07864] i.c.s.RepairRunner - Next segment to run : 4ed04e40-ff00-11ec-a134-1b2df3c07864 
INFO   [2022-07-08 20:58:32,667] [SchedulingManagerTimer] i.c.s.SchedulingManager - Repair schedule '5147f450-fe58-11ec-97bf-51955d7aec44' is paused 
INFO   [2022-07-08 20:58:45,853] [cassandra:4ecfb200-ff00-11ec-a134-1b2df3c07864] i.c.s.RepairRunner - Attempting to run new segment... 
INFO   [2022-07-08 20:58:45,864] [cassandra:4ecfb200-ff00-11ec-a134-1b2df3c07864] i.c.s.RepairRunner - Next segment to run : 4ed07550-ff00-11ec-a134-1b2df3c07864 
INFO   [2022-07-08 20:59:19,979] [cassandra:4ecfb200-ff00-11ec-a134-1b2df3c07864] i.c.s.RepairRunner - Attempting to run new segment... 

```

Nodetool info for each node

```
Pod cassandra-0
ID                     : 63f8aa38-06b4-44cd-92a2-37e7074e0455
Gossip active          : true
Native Transport active: true
Load                   : 1.89 GiB
Generation No          : 1657313463
Uptime (seconds)       : 3813
Heap Memory (MB)       : 476.88 / 5120.00
Off Heap Memory (MB)   : 208.66
Data Center            : datacenter1
Rack                   : rack1
Exceptions             : 0
Key Cache              : entries 28550, size 4.37 MiB, capacity 100 MiB, 236768 hits, 272199 requests, 0.870 recent hit rate, 14400 save period in seconds
Row Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, NaN recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 50 MiB, 0 hits, 0 requests, NaN recent hit rate, 7200 save period in seconds
Percent Repaired       : 89.51556470655855%
Token                  : (invoke with -T/--tokens to see all 256 tokens)

Pod cassandra-1
ID                     : 22809334-476a-443a-927a-caeadde6147f
Gossip active          : true
Native Transport active: true
Load                   : 1.9 GiB
Generation No          : 1657313162
Uptime (seconds)       : 4068
Heap Memory (MB)       : 3115.04 / 5120.00
Off Heap Memory (MB)   : 88.50
Data Center            : datacenter1
Rack                   : rack1
Exceptions             : 0
Key Cache              : entries 28357, size 4.36 MiB, capacity 100 MiB, 305962 hits, 337363 requests, 0.907 recent hit rate, 14400 save period in seconds
Row Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, NaN recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 50 MiB, 0 hits, 0 requests, NaN recent hit rate, 7200 save period in seconds
Percent Repaired       : 89.70026130667003%
Token                  : (invoke with -T/--tokens to see all 256 tokens)

Pod cassandra-2
ID                     : a14dc982-362d-4c68-90d1-cb7915a6f8df
Gossip active          : true
Native Transport active: true
Load                   : 1.9 GiB
Generation No          : 1657312920
Uptime (seconds)       : 4322
Heap Memory (MB)       : 2890.04 / 5120.00
Off Heap Memory (MB)   : 102.07
Data Center            : datacenter1
Rack                   : rack1
Exceptions             : 0
Key Cache              : entries 29388, size 4.46 MiB, capacity 100 MiB, 298952 hits, 331132 requests, 0.903 recent hit rate, 14400 save period in seconds
Row Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, NaN recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 50 MiB, 0 hits, 0 requests, NaN recent hit rate, 7200 save period in seconds
Percent Repaired       : 90.64904204290283%
Token                  : (invoke with -T/--tokens to see all 256 tokens)
```

Nodetool compactionstats and netstats appear normal to me. repair_admin shows the repair as "Running" with the last activity set to roughly not long after it started.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1637) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1637
┆priority: Medium

### PR DESCRIPTION
**Pull request by Miles-Garnsey**
Ensure that, in an incremental repair, the replica list is updated on every repair run. This addresses cases where the node IPs change.

Fixes https://github.com/thelastpickle/cassandra-reaper/issues/1213

### CODE REVIEW

**Comment by Miles-Garnsey** [comment]
This is still a work in progress. I have written a test (which is passing), but it isn't clear to me that this should actually be working.

1. On line 470 I make a call to `clusterFacade.getRangeToEndpointMap` without actually having called `.connect`. 
2. When attempting to extract the token range from `segment`, I only extract the first and last tokens. I need to confirm that this will work even when vnodes are present (although given my limited understanding of what a segment is, I think it may be OK?)

**Comment by Miles-Garnsey** [comment]
Manual testing of this change suggests that there are possible improvements still available, but that it does address the specific requirements in the ticket.

First, I tried starting the repair, pausing it, then doing a rolling restart on the cluster. I've included a log below showing the results. The problem there was that no coordinators could be found. [test-dc1-reaper-94769775c-npd4n.log](https://github.com/thelastpickle/cassandra-reaper/files/9885112/test-dc1-reaper-94769775c-npd4n.log)

But that problem is subtly different to the one we are trying to address here. The matter at hand is not dealing with a full rolling restart (where every IP changes) but just the case where one node's IP changes. I recommend creating another ticket to handle this more extreme case by redoing the DNS lookup so that the list of potential coordinators is refreshed for cases where an FQDN is used as the contact point.

So to make this test more specific I created a new repair, paused it, took note of the host which the current segment was running against, and restarted just that node (leaving the other two in place). 

I do still get the below error, but the repair appears to reschedule correctly:

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at io.cassandrareaper.service.RepairRunner.isAllowedToRun(RepairRunner.java:267)
	at io.cassandrareaper.service.RepairRunner.run(RepairRunner.java:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

You'll note from the below screenshot that it does switch to a different coordinator for the second two segments, which I think is the behaviour we want.

Screen Shot 2022-10-28 at 2 59 15 pm

**Comment by Miles-Garnsey** [comment]
We took this back to the drawing board because our JMX calls were not returning any way to identify the primary replica when doing range -> endpoint queries.

This new approach instead tracks the hostID associated with a given segment and looks up the current IP associated with it when starting each run. It then uses that IP as the coordinator to ensure we are hitting the same endpoint even if the IP has changed.

**Review by adejanovski — APPROVED** [review]
Awesome sauce @Miles-Garnsey! Approved ✅

**Pull request merged**
