### PR TITLE
Code improvements based on SonarQube analysis

### PR DESCRIPTION
**Pull request by adejanovski**

### CODE REVIEW

**Comment by adejanovski** [comment]
SonarQube analysis reported 6 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CommonTools.java#L97](https://github.com/thelastpickle/cassandra-reaper/blob/68a3b6209a867ae1ddb6fc735beacb0e4df0b890/src/main/java/com/spotify/reaper/resources/CommonTools.java#L97): Remove this unused private "generateSegments" method. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [RepairRunner.java#L295](https://github.com/thelastpickle/cassandra-reaper/blob/68a3b6209a867ae1ddb6fc735beacb0e4df0b890/src/main/java/com/spotify/reaper/service/RepairRunner.java#L295): Remove this unused private "repairSegment" method. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [SchedulingManager.java#L45](https://github.com/thelastpickle/cassandra-reaper/blob/68a3b6209a867ae1ddb6fc735beacb0e4df0b890/src/main/java/com/spotify/reaper/service/SchedulingManager.java#L45): Invoke method(s) only conditionally. Use the built-in formatting to construct this argument. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AS2629)
1. ![MAJOR][MAJOR] [SchedulingManager.java#L56](https://github.com/thelastpickle/cassandra-reaper/blob/68a3b6209a867ae1ddb6fc735beacb0e4df0b890/src/main/java/com/spotify/reaper/service/SchedulingManager.java#L56): Invoke method(s) only conditionally. Use the built-in formatting to construct this argument. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AS2629)
1. ![MAJOR][MAJOR] [SchedulingManager.java#L113](https://github.com/thelastpickle/cassandra-reaper/blob/68a3b6209a867ae1ddb6fc735beacb0e4df0b890/src/main/java/com/spotify/reaper/service/SchedulingManager.java#L113): Invoke method(s) only conditionally. Use the built-in formatting to construct this argument. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AS2629)
1. ![MAJOR][MAJOR] [SegmentRunner.java#L321](https://github.com/thelastpickle/cassandra-reaper/blob/68a3b6209a867ae1ddb6fc735beacb0e4df0b890/src/main/java/com/spotify/reaper/service/SegmentRunner.java#L321): Remove this unused private "repairHasSegmentRunning" method. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Comment by adejanovski** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CommonTools.java#L97](https://github.com/thelastpickle/cassandra-reaper/blob/1d97d73a1da418de408070130f3f97e96afe1a6a/src/main/java/com/spotify/reaper/resources/CommonTools.java#L97): Remove this unused private "generateSegments" method. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [RepairRunner.java#L295](https://github.com/thelastpickle/cassandra-reaper/blob/1d97d73a1da418de408070130f3f97e96afe1a6a/src/main/java/com/spotify/reaper/service/RepairRunner.java#L295): Remove this unused private "repairSegment" method. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [SegmentRunner.java#L321](https://github.com/thelastpickle/cassandra-reaper/blob/1d97d73a1da418de408070130f3f97e96afe1a6a/src/main/java/com/spotify/reaper/service/SegmentRunner.java#L321): Remove this unused private "repairHasSegmentRunning" method. [rule](https://sonarqube.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Comment by michaelsembwever** [comment]
can we put 24 hours wait time between creation (or last comment) and merge? difficult for all to get a say otherwise.

my question around this is, and it may no longer be relevant to this specific PR, is what's the status of Spotify's original reaper repo? I see that they are still accepting commits?

**Comment by adejanovski** [comment]
@michaelsembwever : sure, that one was really about tidying the codebase based on SonarQube feedback, but you're right for the wait. On top of that I left a file that shouldn't be in there in the PR.

Based on what I see, the original Spotify repo is only merging internal PRs and there's no plan to reintegrate our fork for now.

**Pull request merged**
