### PR TITLE
Add intellij IDEA code style settings and update dev documentation to…

### LINKED ISSUE #1338: Add IDEA editor config to docs to support checkstyle compatible reformat rules
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=35526662)

The checkstyle rules in this repo are very extensive, and getting editor configurations which are compatible with our checkstyle rules is a time consuming game of trial and error for new contributors (or current contributors who accidentally lose them - like me).

I suggest we export a set of IntelliJ IDEA rules and place them in the docs directory for the use of contributors, to save them struggling against endless checkstyle errors.

# Definition of done

An XML file containing intelliJ code style rules is present in the repo, and provides intelliJ rules which are compatible with our checkstyle rules.

### PR DESCRIPTION
**Pull request by Miles-Garnsey**
Add intellij IDEA code style settings and update dev documentation to describe location of new configuration xml file.

Fixes #1338

### CODE REVIEW

**Comment by burmanm** [comment]
I'm not sure if this file is supposed to have this info, but there's no automated header inclusion:

[ERROR] /Users/michael.burman/projects/datastax/cassandra-reaper/src/server/src/main/java/io/cassandrareaper/management/http/models/Job.java:2: Line does not match expected header line of ' * Licensed under the Apache License, Version 2.0 \(the "License"\);'. [RegexpHeader]
[ERROR] /Users/michael.burman/projects/datastax/cassandra-reaper/src/server/src/main/java/io/cassandrareaper/management/http/models/Job.java:6: 'package' should be separated from previous statement. [EmptyLineSeparator]
[ERROR] /Users/michael.burman/projects/datastax/cassandra-reaper/src/server/src/main/java/io/cassandrareaper/management/http/models/JobStatusTracker.java:1: Missing a header - not enough lines in file. [RegexpHeader]

etc

The checkstyle rules require that one. Otherwise I haven't seen an issue yet.

**Comment by Miles-Garnsey** [comment]
@burmanm thanks for mentioning the file header, indeed my current solution doesn't address this. I'm not sure how to do so given that there is no `export` option on the file template config screen in intelliJ. 

If you have suggestions on how to add this to the config please feel free to PR a new config file into my branch and I'll be pleased to merge it.

**Comment by burmanm** [comment]
I don't know if this approach works, but in the Cassandra project at least, it's done the following way. There's a folder called ``.idea`` which is generated and that has ``.idea/copyright`` directory with two files, ``profiles_settings.xml`` and ``Apache_License_2_0.xml`` and the ``profiles_settings.xml``sets

```xml
<settings default="Apache License 2.0" />
```

Which matches the Apache file's:

```xml
<component name="CopyrightManager">
  <copyright>
    <option name="myName" value="Apache License 2.0" />
```

Works on my IDEA at least, it's automatically set as the default copyright target.

**Comment by Miles-Garnsey** [comment]
> I don't know if this approach works, but in the Cassandra project at least, it's done the following way. There's a folder called `.idea` which is generated and that has `.idea/copyright` directory with two files, `profiles_settings.xml` and `Apache_License_2_0.xml` and the `profiles_settings.xml`sets
> 
> ```
> <settings default="Apache License 2.0" />
> ```
> 
> Which matches the Apache file's:
> 
> ```
> <component name="CopyrightManager">
>   <copyright>
>     <option name="myName" value="Apache License 2.0" />
> ```
> 
> Works on my IDEA at least, it's automatically set as the default copyright target.

I don't know if this will work, because we have two copyright holders on this project:

```
* Copyright 2014-2017 Spotify AB
 * Copyright 2016-2019 The Last Pickle Ltd
```

If you can figure out how to add the right names in there, then please raise a PR against this branch after manually testing and I'll approve it.

Otherwise, I'd appreciate an approval here so we can clear it off the PRs list.

**Review by burmanm — APPROVED** [review]

**Pull request merged**
