### PR TITLE
Fix SSL encrypted and client authenticating connections to Cassandra's jmx

### PR DESCRIPTION
**Pull request by michaelsembwever**
Previously if the Cassandra node's had `com.sun.management.jmxremote.registry.ssl=true` then reaper would not be able to connect. This was because the rmi port becomes encrypted but the
jmx client in reaper was not configured to use ssl here.

This fix permits jmx rmi encrypted connections when the jvm option `-Dssl.enable=true` is provided.

### CODE REVIEW

**Comment by ossarga** [comment]
Nice work. This looks similar to the way it is implemented in `nodetool`. Do we need a unit test or integration test for this?

**Comment by michaelsembwever** [comment]
> Do we need a unit test or integration test for this?

That would be nice. Any ideas?

**Comment by zznate** [comment]
> That would be nice. Any ideas?

Meh? We would be largely testing functionality of the JDK. Maybe just ensuring we return the right instance if `ssl.enable` is true.

**Comment by michaelsembwever** [comment]
Let's put it in the too hard basket for now. It would be a full integration test run against a newly ssl configured ccm cluster. That's a lot of overhead.

**Comment by michaelsembwever** [comment]
any objections to merging?

**Comment by zznate** [comment]
Nope.

**Comment by ossarga** [comment]
No. These changes look fine. As mentioned, this is pretty much what `nodetool` does.

**Review by ossarga — APPROVED** [review]
@michaelsembwever these changes are really good. You and @zznate have good points about the tests. As mentioned, this is pretty much what `nodetool` does. So lets proceed with the merge.

**Pull request merged**
