### PR TITLE
Fix issue with upgrades on postgres and h2 when coming from pre-0.8 

### LINKED ISSUE #255: 0.7.1 to 0.8-SNAPSHOT (master) upgrade and startup errors (postgres backend)
Hey,

When trying to upgrade from 0.7.1 to 0.8-SNAPSHOT(master rev f188f92074ea897ffaa711ee9f7283bc865a2095), the service generates the following stack trace and stops.

Let me know if I can provide more information.

Thank you.

  J.

`==> /var/log/cassandra-reaper.log <==
Looking for reaper in /usr/share/cassandra-reaper/
Worker started
INFO   [2017-10-27 20:49:17,808] [main] i.d.s.DefaultServerFactory - Registering jersey handler with root path prefix: /
INFO   [2017-10-27 20:49:17,812] [main] i.d.s.DefaultServerFactory - Registering admin handler with root path prefix: /
INFO   [2017-10-27 20:49:17,812] [main] i.d.a.AssetsBundle - Registering AssetBundle with name: assets for path /webui/*
INFO   [2017-10-27 20:49:17,840] [main] i.c.ReaperApplication - initializing runner thread pool with 16 threads
INFO   [2017-10-27 20:49:17,846] [main] i.c.ReaperApplication - initializing storage of type: database
INFO   [2017-10-27 20:49:18,012] [main] o.f.c.i.u.VersionPrinter - Flyway 4.0.3 by Boxfuse
INFO   [2017-10-27 20:49:18,060] [main] o.f.c.i.d.DbSupportFactory - Database: jdbc:postgresql://127.0.0.1/reaper (PostgreSQL 9.5)
INFO   [2017-10-27 20:49:18,142] [main] o.f.c.i.m.MetaDataTableImpl - Repair of failed migration in metadata table "public"."schema_version" not necessary. No failed migration detected.
INFO   [2017-10-27 20:49:18,154] [main] o.f.c.i.c.DbRepair - Successfully repaired metadata table "public"."schema_version" (execution time 00:00.015s).
INFO   [2017-10-27 20:49:18,210] [main] o.f.c.i.c.DbValidate - Successfully validated 4 migrations (execution time 00:00.009s)
INFO   [2017-10-27 20:49:18,236] [main] o.f.c.i.c.DbMigrate - Current version of schema "public": 3.0.0
INFO   [2017-10-27 20:49:18,237] [main] o.f.c.i.c.DbMigrate - Schema "public" is up to date. No migration necessary.
INFO   [2017-10-27 20:49:18,458] [main] i.c.ReaperApplication - no JMX connection factory given in context, creating default
INFO   [2017-10-27 20:49:18,461] [main] i.c.ReaperApplication - creating and registering health checks
INFO   [2017-10-27 20:49:18,461] [main] i.c.ReaperApplication - creating resources and registering endpoints
INFO   [2017-10-27 20:49:19,473] [main] i.c.s.SchedulingManager - Starting new SchedulingManager instance
INFO   [2017-10-27 20:49:19,473] [main] i.c.ReaperApplication - Initializing JMX seed list for all clusters...
INFO   [2017-10-27 20:49:19,489] [main] i.c.j.JmxConnectionsInitializer - Initializing JMX seed list for cluster ilandcorecluster...
INFO   [2017-10-27 20:49:20,158] [main] i.c.ReaperApplication - Initialized JMX seed list for all clusters.
INFO   [2017-10-27 20:49:20,158] [main] i.c.ReaperApplication - resuming pending repair runs

==> /var/log/cassandra-reaper.err <==
Exception in thread "main" java.lang.NullPointerException
        at io.cassandrareaper.storage.postgresql.RepairUnitMapper.map(RepairUnitMapper.java:33)
        at io.cassandrareaper.storage.postgresql.RepairUnitMapper.map(RepairUnitMapper.java:27)
        at org.skife.jdbi.v2.Query$4.munge(Query.java:183)
        at org.skife.jdbi.v2.QueryResultSetMunger.munge(QueryResultSetMunger.java:41)
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1344)
        at org.skife.jdbi.v2.Query.fold(Query.java:173)
        at org.skife.jdbi.v2.Query.first(Query.java:273)
        at org.skife.jdbi.v2.Query.first(Query.java:264)
        at org.skife.jdbi.v2.sqlobject.ResultReturnThing$SingleValueResultReturnThing.result(ResultReturnThing.java:110)
        at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:43)
        at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:43)
        at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:212)
        at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:127)
        at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$adabcadb.getRepairUnit(<generated>)
        at io.cassandrareaper.storage.PostgresStorage.getRepairUnit(PostgresStorage.java:270)
        at io.cassandrareaper.service.RepairManager.abortSegments(RepairManager.java:142)
        at io.cassandrareaper.service.RepairManager.abortSegmentsWithNoLeader(RepairManager.java:128)
        at io.cassandrareaper.service.RepairManager.resumeRunningRepairRuns(RepairManager.java:91)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:224)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:67)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:75)
        at io.dropwizard.Application.run(Application.java:79)
        at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:87)
`

### PR DESCRIPTION
**Pull request by adejanovski**
This PR fixes #255 by handling null values in newly added arrays in the repair_schedule table.

### CODE REVIEW

**Comment by anguenot** [comment]
@adejanovski  just tested the branch. Got another stack trace:

`==> /var/log/cassandra-reaper.err <==
Exception in thread "main" java.lang.IllegalStateException: if endTime is set, so must startTime be set
        at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
        at io.cassandrareaper.core.RepairSegment$Builder.build(RepairSegment.java:182)
        at io.cassandrareaper.storage.postgresql.RepairSegmentMapper.map(RepairSegmentMapper.java:48)
        at io.cassandrareaper.storage.postgresql.RepairSegmentMapper.map(RepairSegmentMapper.java:26)
        at org.skife.jdbi.v2.Query$4.munge(Query.java:183)
        at org.skife.jdbi.v2.QueryResultSetMunger.munge(QueryResultSetMunger.java:41)
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1344)
        at org.skife.jdbi.v2.Query.fold(Query.java:173)
        at org.skife.jdbi.v2.Query.list(Query.java:82)
        at org.skife.jdbi.v2.sqlobject.ResultReturnThing$IterableReturningThing.result(ResultReturnThing.java:253)
        at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:43)
        at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:43)
        at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:212)
        at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:127)
        at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$57c5ffbf.getRepairSegmentsForRun(<generated>)
        at io.cassandrareaper.storage.PostgresStorage.getRepairSegmentsForRun(PostgresStorage.java:329)
        at io.cassandrareaper.service.RepairRunner.<init>(RepairRunner.java:93)
        at io.cassandrareaper.service.RepairManager.startRunner(RepairManager.java:225)
        at io.cassandrareaper.service.RepairManager.startRepairRun(RepairManager.java:205)
        at io.cassandrareaper.service.RepairManager.resumeRunningRepairRuns(RepairManager.java:105)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:224)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:67)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:75)
        at io.dropwizard.Application.run(Application.java:79)
        at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:87)
`

**Review by michaelsembwever — APPROVED** [review]
LGTM

**Comment by adejanovski** [comment]
Thanks for testing the PR @anguenot !

The other issue you ran into is identified and will be fixed in the misnamed #261, as it also hits the Postgres and H2 backends.

**Comment by anguenot** [comment]
@adejanovski  thank YOU for the quick fix! You guys want me to test #261?

**Comment by adejanovski** [comment]
@anguenot : I have another fix to push to #261 before it's ready for testing with postgres/h2.

I'll ping you when it's ready.

**Pull request merged**
