### PR TITLE
Implement compaction methods in the HttpManagementProxy (fixes #1340)

### LINKED ISSUE #1340: Implement compaction methods in the HttpManagementProxy
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=35567380)

## Definition of Done
- [x] the `forceKeyspaceCompaction()` method is implemented in the HttpCassandraManagementProxy class
- [x] the `getCompactions()` method is implemented in the HttpCassandraManagementProxy class
- [x] the `getCompactionParameters()` method is implemented in the HttpCassandraManagementProxy class

### PR DESCRIPTION
**Pull request by olim7t**
TODO:
- [x] merge k8ssandra/management-api-for-apache-cassandra#365 and generate new API client

### CODE REVIEW

**Review by emerkle826 — COMMENTED** [review]
This looks good. We will want to merge #1372 into the integration branch, and then perhaps rebase this branch on top of that, but I have tried it locally and the tests that were passing before are now passing again.

**Comment by olim7t** [comment]
> This looks good. We will want to merge #1372 into the integration branch, and then perhaps rebase this branch on top of that

Done

**Review by Miles-Garnsey — DISMISSED** [review]
Approving as discussed now tests pass. **EDIT: hang on -  where are the tests?**

**Comment by olim7t** [comment]
Forced-push to rebase and add unit tests.

**Review by Miles-Garnsey — APPROVED** [review]
Looks great, approving and merging!

**Pull request merged**
