### PR TITLE
Migrate the forgotten unused AddClusterIT and basic_reaper_functionality.feature into BasicSteps and integration_reaper_functionality.feature

### PR DESCRIPTION
**Pull request by michaelsembwever**
- Migrate scenarios from basic_reaper_functionality.feature into integration_reaper_functionality.feature
 - Remove Incremental/NoIncremental class variations where they are not used.
 - Remove `@full` annotation, as only presence @incremental is ever checked.
 - Small fix to RepairScheduleService.isConflictingSchedules(..)
 - Remove failsafe plugin from pom as it's not used.
 -  reduce log noise in integration tests
 - consistent ccm datacenter names in CI, and correctly configured DcAwareLoadBalancing policy (localDC is always 'dc1')
 - in BasicSteps assert that responses are only empty on against 2xx responses
 - in ReaperTestJettyRunner ignore interruption exceptions during test shutdown

### CODE REVIEW

**Review by ossarga — APPROVED** [review]
I tested this branch by running

```
mvn -Dtest=BasicSteps test
```

These changes look good to merge.

**Comment by michaelsembwever** [comment]
> `mvn -Dtest=BasicSteps test`

That won't work.
To test this run the integration tests.

```
mvn clean install
mvn surefire:test -Dtest=ReaperIT
mvn surefire:test -Dtest=ReaperCassandraIT
```
(making sure jmx ports and authentication match that of your local ccm running)

**Comment by ossarga** [comment]
I re-ran the tests as suggested using a single node and a three node cluster in `ccm`. All the tests passed on both clusters. Let's merge this PR.

**Comment by michaelsembwever** [comment]
thanks @ossarga

**Pull request merged**
