### PR TITLE
JDK11 fixes

### PR DESCRIPTION
**Pull request by burmanm**
This is the changes so far. It compiles, but some tests fail still.

### CODE REVIEW

**Comment by adejanovski** [comment]
Cool stuff! JDK11 support is something we really need now for Reaper.
I'll try to find some time to check the failing tests.

**Comment by burmanm** [comment]
Why is it testing 1.4.1 jar?

```
java.lang.AssertionError: ClassNotFoundException for io.cassandrareaper.ReaperApplication in shaded versioned jarfile file:/home/michael/projects/git/datastax/cassandra-reaper/src/server/test-jars/cassandra-reaper-1.4.1.jar
```

I think these fail because JDK11 has stricter class loader and modules.

**Comment by michaelsembwever** [comment]
> Why is it testing 1.4.1 jar?

Upgrade tests. They need fixing

**Comment by adejanovski** [comment]
Merged in #1149

**Pull request closed without merging**
