### PR TITLE
Fix bower build, docker build and one k8ssandra bug

### PR DESCRIPTION
**Pull request by burmanm**
* Fixing #987 by installing bash to the docker image and also updated the Alpine image to a maintained version.
* Fix the bower.json build by taking care of the dependency issue (conflict with the font-awesome versions)
* k8ssandra could in a certain edge case (cluster goes down, user deletes it from reaper and then restarts the cluster) call the addCluster again for an existing cluster and that could cause the seeds to get corrupted inside Reaper. Only update the seeds in re-add of existing cluster in addCluster if dynamicSeeds is enabled.

### CODE REVIEW

**Review by adejanovski — APPROVED** [review]
Great much needed fixes! Thanks @burmanm 👍

**Comment by adejanovski** [comment]
@burmanm, could we point the PR to the `2.1` branch instead of `master`?
These are all bug fixes which will be released quicker in 2.1 rather than waiting for our next minor.

Thanks!

**Comment by michaelsembwever** [comment]
I can't make heads or tails of this PR, with its 16 commits.
Could this please be cleaned up so it's possible to review…

**Comment by burmanm** [comment]
It's the change of base with those merge commits that messes it up (the original branch is against master). The real commits are the last four.

**Comment by adejanovski** [comment]
Merged as part of #1002

**Pull request closed without merging**
