### PR TITLE
Fix #453 - Add auth with encrypted password sample

### LINKED ISSUE #453: Does Reaper have capability to encrypt the shiro.ini file
**Spotted on 1.2.0-BETA-20180607 (21edbeb)**

Dear Reaper team,

Can you guide if shiro.ini file for storing the user id and password can be encrypted on disk so that the plain text password can be protected?

Thanks for all the support so far!

Regards,
Gagan

### PR DESCRIPTION
**Pull request by nsteinmetz**
* Fix #453 with sample in doc

### CODE REVIEW

**Comment by adejanovski** [comment]
Hi @nsteinmetz, 

that's a very valuable addition to the docs.
Even if one might find it trivial (I don't :) ), could you add the instructions to get the sha256 hash from a password ?

Otherwise LGTM !

**Comment by nsteinmetz** [comment]
Hi @adejanovski,

Ok, I will early next week :)

**Comment by nsteinmetz** [comment]
Hi @adejanovski ; done - let me know if it's ok for you.

**Review by adejanovski — APPROVED** [review]
Awesome! Thanks!

**Pull request merged**
